complexity:
  TooManyFunctions:
    active: false
    ignorePrivate: true
  LongParameterList:
    active: false
  ComplexMethod:
    active: false
  LongMethod:
    active: false
  NestedBlockDepth:
    active: false
  ComplexCondition:
    active: false

style:
  # Numbers are used for enums and blur algorithms matrices
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  NewLineAtEndOfFile:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  UnusedPrivateMember:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  PrintStackTrace:
    active: false
  SwallowedException:
    active: false

naming:
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9_]*)*'
  ConstructorParameterNaming:
    active: false
  VariableNaming:
    active: false
