complexity:
  TooManyFunctions:
    active: true
    ignorePrivate: true
  LongParameterList:
    active: true
  ComplexMethod:
    active: true
  LongMethod:
    active: true
  NestedBlockDepth:
    active: true
  ComplexCondition:
    active: true
  StringLiteralDuplication:
    active: true
    threshold: 4

style:
  # Numbers are used for enums and blur algorithms matrices
  MagicNumber:
    active: true
  WildcardImport:
    active: true
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
  ReturnCount:
    active: true
  UnusedPrivateMember:
    active: true
  UnnecessaryParentheses:
    active: true
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  UseIfInsteadOfWhen:
    active: true
  ExpressionBodySyntax:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  SpacingBetweenPackageAndImports:
    active: true

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

comments:
  CommentOverPrivateProperty:
    active: false
  CommentOverPrivateFunction:
    active: false
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true
  PrintStackTrace:
    active: true
  SwallowedException:
    active: true

potential-bugs:
  LateinitUsage:
    active: false

naming:
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9_]*)*'
  ConstructorParameterNaming:
    active: true
  VariableNaming:
    active: true
  FunctionMaxLength:
    active: true

formatting:
  # We already have MaxLineLength from detekt, which is suppressed in few cases. This rule cannot be suppressed with annotations
  MaximumLineLength:
    active: false
  # We already have PackageName from detekt
  PackageName:
    active: false
  MultiLineIfElse:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  SpacingBetweenDeclarationsWithComments:
    active: true
    autoCorrect: true
  ArgumentListWrapping:
    active: true
    autoCorrect: false
  NoUnusedImports:
    active: true
    autoCorrect: true
  ParameterListWrapping:
    active: false